replicaCount: 1
image:
  pullPolicy: Always
  repository: quay.io/ortelius/ms-general
  tag: main-v10.0.452-g68e847
  sha: sha256:3d229e3e1b5b9ffd536b6f459985cbbdd6066d88791cf87c4168af83f224ee4b
internal_nginx: "OFF"
